refactor: refactor the project design 2th

diff --git a/bin/ngxway b/bin/ngxway
--- a/bin/ngxway
+++ b/bin/ngxway
@@ -48,9 +48,16 @@ function start(){
     exit 1
   fi
 
-  # Exec command
+  # Exec command: reload the nginx
   # docker exec -it ngxwayContainer /bin/sh
-  docker exec -d ngxwayContainer bash nginx/reload.sh
+  docker exec -d ngxwayContainer bash /dist/scripts/nginx_reload.sh
+  if [ $? -ne 0 ]; then
+    echo -e ">>>>>>>>Start failure: failed to exec<<<<<<<<"
+    exit 1
+  fi
+
+  # Exec command: start the go server
+  docker exec -d ngxwayContainer /dist/bin/goserver
   if [ $? -ne 0 ]; then
     echo -e ">>>>>>>>Start failure: failed to exec<<<<<<<<"
     exit 1
